version: '3.9'
services:
  rustfs:
    image: rustfs/rustfs:1.0.0-beta.10@sha256:60f4f2f41ce95216f8cac676e69f9d90c0bfec458a3bc7fd7fb9b7c2452ac57a
    hostname: rustfs
    container_name: rustfs__rustfs
    restart: unless-stopped

    environment:
      - RUSTFS_ACCESS_KEY=root
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}

    volumes:
      - type: bind
        source: /data/rustfs/data
        target: /data

      - type: bind
        source: /data/rustfs/logs
        target: /logs

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 8192m

  cloudflared:
    image: cloudflare/cloudflared:2026.7.2-amd64@sha256:18626b1baac4450214535cd5bc40ef44c0635244d585ebf707749c22b6f3408f
    hostname: cloudflared
    container_name: rustfs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 4096m

networks:
  default:
    name: rustfs__default
