version: '3.9'
services:
  rustfs:
    image: rustfs/rustfs:1.0.1@sha256:1803faef57627e2d9c2e7d89d655d712ddded5389040054987163043fecb6a3c
    hostname: rustfs
    container_name: rustfs__rustfs
    restart: unless-stopped

    environment:
      - RUSTFS_ACCESS_KEY=root
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}

    volumes:
      - type: bind
        source: /data/rustfs/data
        target: /data

      - type: bind
        source: /data/rustfs/logs
        target: /logs

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 8192m

  cloudflared:
    image: cloudflare/cloudflared:2026.10.0-amd64@sha256:1a50cc8893b3f0dd283805d2efcd3336210aced60a83d967fb2bbc8ab69b5f35
    hostname: cloudflared
    container_name: rustfs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 4096m

networks:
  default:
    name: rustfs__default
