version: '3.9'
services:
  rustfs:
    image: rustfs/rustfs:1.0.0@sha256:8cc9801755448b71a786705ce76692c77e14936cccd87cf2fc31842e58f4d1ff
    hostname: rustfs
    container_name: rustfs__rustfs
    restart: unless-stopped

    environment:
      - RUSTFS_ACCESS_KEY=root
      - RUSTFS_SECRET_KEY=${RUSTFS_SECRET_KEY}

    volumes:
      - type: bind
        source: /data/rustfs/data
        target: /data

      - type: bind
        source: /data/rustfs/logs
        target: /logs

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 8192m

  cloudflared:
    image: cloudflare/cloudflared:2026.9.1-amd64@sha256:d68fa057087c359c79a255570e891215877ce48aa48ba6f28aac90d8077acbc3
    hostname: cloudflared
    container_name: rustfs__cloudflared
    restart: unless-stopped

    environment:
      TUNNEL_METRICS: 0.0.0.0:9126
      TUNNEL_LOGFILE: /dev/stdout

    command: tunnel run --token ${TUNNEL_TOKEN}

    networks:
      default:

    deploy:
      resources:
        limits:
          memory: 4096m

networks:
  default:
    name: rustfs__default
